export const NONE = 'None'

export const categories = {
  'General': 'general',
  'Business': 'business', 
  'Entertainment': 'entertainment', 
  'Health': 'health', 
  'Science': 'science', 
  'Sports': 'sports', 
  'Technology': 'technology'
}

export const countries = {
  'Argentina': 'ar',
  'Australia': 'au',
  'Austria': 'at',
  'Belgium': 'be',
  'Brazil': 'br',
  'Bulgaria': 'bg',
  'Canada': 'ca',
  'China': 'cn',
  'Colombia': 'co',
  'Czech Republic': 'cz',
  'Egypt': 'eg',
  'France': 'fr',
  'Germany': 'de',
  'Greece': 'gr',
  'Hong Kong': 'hk',
  'Hungary': 'hu',
  'India': 'in',
  'Indonesia': 'id',
  'Ireland': 'ie',
  'Israel': 'il',
  'Italy': 'it',
  'Japan': 'jp',
  'Latvia': 'lv',
  'Lithuania': 'lt',
  'Malaysia': 'my',
  'Mexico': 'mx',
  'Moroco': 'ma',
  'Netherlands': 'nl',
  'New Zealand': 'nz',
  'Nigeria': 'ng',
  'Norway': 'no',
  'Phillipines': 'ph',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Romania': 'ro',
  'Saudi Arabia': 'sa',
  'Serbia': 'rs',
  'Singapore': 'sg',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'South Africa': 'sa',
  'South Korea': 'kr',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Taiwan': 'tw',
  'Thailand': 'th',
  'Turkey': 'tr',
  'UAE': 'ae',
  'Ukraine': 'ua',
  'United Kingdom': 'gb',
  'United States': 'us',
  'Venezuela': 've'
}

export const languages = {
  'Arabic': 'ar', 
  'German': 'de', 
  'English': 'en', 
  'Spanish': 'es', 
  'French': 'fr', 
  'Hebrew': 'he', 
  'Italian': 'it', 
  'Dutch': 'nl', 
  'Norwegian': 'no', 
  'Portuguese': 'pt', 
  'Russian': 'ru', 
  'Swedish': 'se', 
  'Chinese': 'zh' 
}